plugins:
  - rubocop-rails
  - rubocop-performance

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4.1
  Exclude:
    - "Guardfile"
    - "test/integration/password_resets_test.rb"
    - "config/environments/*"

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "Guardfile"
    - "db/migrate/*"
    - "test/integration/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true

Rails:
  Enabled: true
